version: '3.4'

services:
  afnarqui.prueba.services.webapi:
    image: ${DOCKER_REGISTRY-}afnarquipruebaserviceswebapi
    build:
      context: .
      dockerfile: Afnarqui.Prueba.Services.WebApi/Dockerfile
